### ISSUE TITLE
Consider switching base image to Debian buster or Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by derek-gfs** [docker-library/httpd#122]
A fully patched image of Debian 9 "Stretch" comes with a number of security vulnerabilities (133) as compared to Ubuntu 18.04 LTS (34).

Since Apache is typically a forward-facing part of a system architecture, security of the image OS should be a top priority.

Consider switching the default build to use a glibc build such as Debian sid, Ubuntu 18.04 or recent versions of Centos to reduce the number of vulnerabilities while maintaining glibc compatibility.

Below is a list of the vulnerabilities in Debian 9 "Stretch", 5 of which have a CVSS score higher than 9.

CVE-2017-1000082
CVE-2017-12762
CVE-2005-2541
CVE-2018-15686
CVE-2017-16997
CVE-2008-4609
CVE-2018-14616
CVE-2017-18269
CVE-2017-14062
CVE-2018-1000654
CVE-2018-14610
CVE-2018-14613
CVE-2018-14614
CVE-2017-15804
CVE-2018-6954
CVE-2018-14611
CVE-2018-6551
CVE-2018-1000001
CVE-2017-12424
CVE-2017-1000379
CVE-2018-12930
CVE-2017-9986
CVE-2013-7445
CVE-2018-14612
CVE-2018-6485
CVE-2016-2779
CVE-2018-12931
CVE-2017-1000408
CVE-2017-11164
CVE-2017-15670
CVE-2014-9892
CVE-2016-10723
CVE-2018-1049
CVE-2016-8660
CVE-2018-7273
CVE-2018-6829
CVE-2005-3660
CVE-2018-13100
CVE-2018-1108
CVE-2017-5130
CVE-2018-11237
CVE-2017-16932
CVE-2016-9318
CVE-2017-13693
CVE-2018-13093
CVE-2010-5321
CVE-2017-7246
CVE-2017-18258
CVE-2010-4052
CVE-2010-0928
CVE-2017-18078
CVE-2017-1000409
CVE-2007-5686
CVE-2015-3276
CVE-2017-8872
CVE-2017-7245
CVE-2018-12929
CVE-2010-4756
CVE-2018-13095
CVE-2018-18690
CVE-2018-13097
CVE-2016-10228
CVE-2018-10322
CVE-2018-14625
CVE-2018-7169
CVE-2018-12928
CVE-2013-0340
CVE-2010-4051
CVE-2017-17740
CVE-2018-9234
CVE-2018-1121
CVE-2004-0230
CVE-2018-10754
CVE-2018-14567
CVE-2017-12132
CVE-2015-8985
CVE-2011-3389
CVE-2012-4542
CVE-2018-11236
CVE-2017-18249
CVE-2018-17972
CVE-2018-13094
CVE-2018-1000026
CVE-2010-4563
CVE-2007-6755
CVE-2018-1128
CVE-2018-14404
CVE-2014-9900
CVE-2018-5848
CVE-2018-3693
CVE-2018-1000168
CVE-2017-15671
CVE-2018-13096
CVE-2017-14159
CVE-2017-13695
CVE-2017-12618
CVE-2018-5995
CVE-2013-4392
CVE-2016-2781
CVE-2015-2877
CVE-2018-18710
CVE-2017-5969
CVE-2017-18232
CVE-2018-5953
CVE-2007-3719
CVE-2017-12613
CVE-2017-0630
CVE-2018-13053
CVE-2018-12896
CVE-2015-8553
CVE-2017-13694
CVE-2018-1129
CVE-2018-8043
CVE-2018-7754
CVE-2017-11472
CVE-2017-18018
CVE-2018-18281
CVE-2018-16868
CVE-2018-6982
CVE-2018-9517

**Comment by tianon** [comment]
Are any of these really actionable? (None of them have available package updates in Debian Stretch, which is still actively supported.)

Are they actively exploitable in the way `httpd` is provided in this image?

Just because they have a high CVSS score does not necessarily mean they're actually a concern for how this image is packaged/used.

Switching the base of this image is a bit of a disruptive change, and switching it away from the still-explicitly-security-supported Debian stable release for the Debian testing release (which is _not_ security supported until it is actually released) or for Ubuntu (which is a different base entirely) is not something we're going to consider lightly.

**Comment by tianon** [comment]
See https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-so-many-cves for a more long-form CVE explanation. :+1:
