### ISSUE TITLE
returned a non-zero code: 2

### ISSUE THREAD

**Issue by GhoctM** [docker-library/httpd#130]

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by GhoctM** [comment]
I have found the cause of the problem, thanks

**Comment by wglambert** [comment]
Cool going to close the issue then.

For future questions you could try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
