### ISSUE TITLE
mod_proxy_html is not included in httpd 2.4

### ISSUE THREAD

**Issue by chris2338** [docker-library/httpd#14]
If I download any other httpd version 2.4 (Windows or Linux), this module is included. Is it an issue?

What is the best way to include it to the official httpd image ?

**Comment by yosifkit** [comment]
I don't see it in the `modules/` directory so it must not be part of the `--enable-mods-shared=most` set.  I am unsure if we should change `most` to `all` or `reallyall` or if that would have adverse effects.

**Comment by denisflorkin** [comment]
Hello I'd also be interested in having certain mods enabled (including  the proxy_http ).
Here I see that the option in the dockerfile (for 2.4) is `enable-mods-shared=reallyall` so I don't understand this :

> I don't see it in the modules/ directory so it must not be part of the --enable-mods-shared=most

The module (proxy_http.so) is in the modules folder when I run the httpd:2.4 image.
Since no a2enmod, and no mods_enabled/available directory, How can I manage activating/installing modules on this image ?

Thanks

**Comment by tianon** [comment]
You need to add an appropriate "LoadModule" directive in your configuration.

**Comment by denisflorkin** [comment]
You're right :) thanks

**Comment by tjaw09a** [comment]
Why is this issue closed?  mod_proxy_html.so is still not included in the image.

**Comment by yosifkit** [comment]
We had thought that `reallyall` would correctly build it but I just tested building it and we are missing a dependency:
```
checking whether to enable mod_xml2enc... checking dependencies
checking for libxml2... checking for libxml2... no
checking whether to enable mod_xml2enc... no (disabled)
checking whether to enable mod_proxy_html... checking dependencies
checking for libxml2... (cached) no
```
I'm working on a pr to fix it.

**Comment by yosifkit** [comment]
Updated #34 to include other missing modules.
