### ISSUE TITLE
modjk

### ISSUE THREAD

**Issue by gkarthiraja** [docker-library/httpd#165]
Recently we are planning to migrate all our application server to docker and we are using httpd as webserver and Guide me or help me how to include or enabled modjk in httpd:2.443.

Thanks.

**Comment by wglambert** [comment]
This repository looks like a good example to go off of for what you're wanting https://github.com/Paritosh-Anand/Docker-Httpd-Tomcat
Essentially you'll need to supply an appropriate configuration to load the modules you want
https://github.com/Paritosh-Anand/Docker-Httpd-Tomcat/blob/28277fe9e81992662a7833b0210900184659a1c4/httpd/apache2.conf#L194-L198

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by gkarthiraja** [comment]
@wglambert thanks for your prompt response. is there any other way to have httpd+modjk without ubuntu or centos image.

**Comment by wglambert** [comment]
Yes you can do `FROM httpd` instead, I was moreso pointing out the `apache2.conf` configuration used.

I'm not sure what dependencies `mod-jk` needs but you should be able to just `apt-get install` them in the Dockerfile

**Comment by yosifkit** [comment]
In order to keep these images as close to upstream releases as possible, these images install Apache Httpd from source. So, you likely won't be able to just install `libapache2-mod-jk` since that pulls in apache modules from `apt` that will likely not work with the image's `httpd`.   You'd instead have to also install [`mod_jk`](https://tomcat.apache.org/download-connectors.cgi) from source as well.

Honestly, it would be simpler to just do `FROM debian:buster` and install `apache2` and `libapache2-mod-jk`. (and if you add `buster-backports`, you can even get version `2.4.43-1~bpo10+1`)
