### ISSUE TITLE
Missing ca-certificates in Debian-based image

### ISSUE THREAD

**Issue by roshanshariff** [docker-library/httpd#175]
The ca-certificates package is missing in the httpd:2.4 image, but present in 2.4-alpine. It is needed for mod_md to work, since it uses libcurl to communicate with the Let's Encrypt ACME servers. The package is installed as a build dependency but then removed afterwards.

To test, inside the container run
```
apt-get update
apt-get -y install curl
curl https://acme-v02.api.letsencrypt.org/directory
```
which gives an error. Then run `apt-get -y install ca-certificates` and repeat.

I would expect ca-certificates to be included in the httpd image, just as it is on the alpine version.

Thanks!

**Comment by tianon** [comment]
The Alpine-based image doesn't explicitly/intentionally contain the `ca-certificates` package -- as seen in https://github.com/docker-library/httpd/blob/077141ee37fca63972292c562ec0f632d0f831b1/2.4/alpine/Dockerfile, it's installed as part of the build dependencies, but then removed.

At this point, we could actually remove it from that `Dockerfile` entirely because Alpine itself now contains enough of that package for the busybox built-in `wget` and `apk`'s usage of TLS to work as expected (which is what you're seeing).

Honestly, I think it's a bit unexpected to need `ca-certificates` inside the `httpd` container because it's not typically going to be making _outbound_ connections unless you've specifically installed/configured something that will do that (such as `mod_md`), so IMO it's not too much to ask that users who need that also install the `ca-certificates` package that's also unique to their usage of the image.
