### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by Kasper886** [docker-library/httpd#176]
The latest version of docker image shows Access Forbidden

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by wglambert** [comment]
Going to close since the issue's too vague, you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
