### ISSUE TITLE
Can't find Apache files

### ISSUE THREAD

**Issue by Gitricity** [docker-library/httpd#223]
Hi. I've set up Apache on Docker using the official image and commands. I can only access the Server through sftp and terminal. The Service set up fine but now when i am accessing the Server through the Browser on Port 8080 it says "Forbidden You don't have permission to access this resource." and i cant find any apache Folder under "user/local" and also not in the docker container/volume. Can anybody help me there?

**Comment by wglambert** [comment]
The Apache2 files are in `/usr/local/`. It might be an issue with the `httpd.conf` configuration

```console
$ docker run -it --rm httpd bash
root@19ae0472527c:/usr/local/apache2# ls -l /usr/local/apache2/
total 40
drwxr-xr-x 2 root root 4096 Oct  5 04:10 bin
drwxr-xr-x 2 root root 4096 Oct  5 04:10 build
drwxr-xr-x 2 root root 4096 Oct  5 04:10 cgi-bin
drwxr-xr-x 4 root root 4096 Oct  5 04:10 conf
drwxr-xr-x 3 root root 4096 Oct  5 04:10 error
drwxr-xr-x 2 root root 4096 Oct  5 04:10 htdocs
drwxr-xr-x 3 root root 4096 Oct  5 04:10 icons
drwxr-xr-x 2 root root 4096 Oct  5 04:10 include
drwxr-xr-x 2 root root 4096 Oct  5 04:10 logs
drwxr-xr-x 2 root root 4096 Oct  5 04:10 modules
```

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
