### ISSUE TITLE
failing to start in openshift due to log file permissions.  

### ISSUE THREAD

**Issue by DrewRay** [docker-library/httpd#30]
is there a better way to log to stdout and stderr than just using proc/self/fd/1

**Comment by bertvannuffelen** [comment]
On this topic, what is the docker way to keep the logs?
Actually now there is only one logs stream (accesible through docker logs <myapache>) but Apache allows to configure per Vhost, per kind of log a stream. This cannot be handled with a single stream approach.
Also for a proxy/webserver, the logs are a critical output. So they need to be materialized on disk. What is the preferred standard approach for docker?

**Comment by tianon** [comment]
Sorry for the long delay.  From what I can tell, Apache upstream only natively supports logging to files or to syslog (https://httpd.apache.org/docs/2.4/da/mod/core.html#errorlog, for example).  If our hacks don't work on OpenShift, then I'd suggest digging in to figure out why (probably AppArmor or SELinux, if I had to guess, but there's a whole host of things it could potentially be).

On the question of multiple log streams, that's not something Docker really _can_ handle natively -- you'd be better off using either files in a volume shared to whatever needs to consume them (Logstash, etc), or attempting to create structured log output such that something like Logstash can recreate the split log data (via prefix or otherwise).

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
