### ISSUE TITLE
environment variables to enable certain modules e.g mod_rewrite?

### ISSUE THREAD

**Issue by babatundebusari** [docker-library/httpd#45]
is it possible to build this into the official image such that one can call certain environment variables to enable certain popular modules? like mod_rewrite?

Thanks

**Comment by Soullivaneuh** [comment]
BTW, what is the current state to enable the mod?

**Comment by tianon** [comment]
Sorry for the delay.  The configuration provided by this image is entirely stock from httpd upstream -- we don't provide any script to help with modification to it.

To enable additional modules, you'll need to update `/usr/local/apache2/conf/httpd.conf` which includes a number of commented-out `LoadModule` lines that will need to be enabled.

Since this is a configuration issue, I'm going to close.  If enabling modules via an environment variable is something you need, I'd recommend creating a short `Dockerfile` which is `FROM httpd:X.Y` and `COPY`s an appropriate script which can then be used when running the image to modify the configuration at runtime instead of at build-time. :+1:
