### ISSUE TITLE
Dockerfile's for armhf Images

### ISSUE THREAD

**Issue by pluttrell** [docker-library/httpd#52]
According to this page: [https://hub.docker.com/r/armhf/httpd/](https://hub.docker.com/r/armhf/httpd/) if we want to find the `Dockerfile`'s used, we need to see the parent project. Reference:

> This image is built from the source of the official image of the same name (httpd). Please see that image's description for links to the relevant Dockerfiles.

The parent's project `Dockerfile` for 2.4.25 is [this file](https://github.com/docker-library/httpd/blob/1883f2ec8be5f2a0cd176673a249c618ad7976ba/2.4/Dockerfile). If I try to build that file, I get an error. I'm assuming to get it to work, I need an `arm` based image...but if I only change the change the `FROM` directive from `FROM debian:jessie-backports` to `FROM resin/rpi-raspbian:latest`, it fails with a different error. So unless I have something else wrong, a different file must have been used to build the images deployed to docker hub.

Where can we get access to the actual `Dockerfile`'s used for the `armhf/httpd` image?

**Comment by yosifkit** [comment]
It is the correct Dockerfile; and is currently built using this Jenkins DSL script: https://github.com/tianon/jenkins-groovy/blob/a3a4bc4db3af3f65c4a318a86bb3d5acc0b9dd83/dsl/docker-multiarch/images/httpd.groovy., which only swaps `FROM debian:jessie-backports` to be `FROM armhf/debian:jessie-backports`.

We are working toward removing the "experimental" status on them and so instead of changing the file, we `docker pull armhf/debian:jessie-backports` and just tag it as `debian:jessie-backports` and then build.  Since in the future, you'll be able to pull `debian:jessie-backports` and get the correct image for your architecture.

**Comment by tianon** [comment]
This has since moved to https://hub.docker.com/r/arm32v7/httpd/, and does include links to the actual `Dockerfile` contents used to build. :+1:
