### ISSUE TITLE
gpg: keyserver receive failed: Address not available

### ISSUE THREAD

**Issue by Protopopys** [docker-library/httpd#66]
Hi! 
If I use  ha.pool.sks-keyservers.net, I have an error :  gpg: keyserver receive failed: Address not available
I change the address to ipv4.pool.sks-keyservers.net. and it work for me.
https://bugs.launchpad.net/ubuntu/+source/gnupg2/+bug/1625845

**Comment by tianon** [comment]
Yes, this is a common issue -- ha.pool.sks-keyservers.net refers to a round-robin pool of many servers, so usually this problem will resolve itself given a little time.  In some repositories, we've resorted to trying multiple servers explicitly (since every server will have issues every now and then), but doing so significantly increases the complexity, and we've hence been hesitant to apply that pattern more comprehensively.
